apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: yatest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # You can adjust this size later if needed
  storageClassName: do-block-storage
