apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: yatest
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15 # Using a recent version of Postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "tododb"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: POSTGRES_PASSWORD
            - name: PGDATA # Add this environment variable
              value: /var/lib/postgresql/data/pgdata # Tell Postgres to use a subdirectory
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
